### ISSUE TITLE
Outdated JSDoc

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#108]
The JSDoc is sometimes outdated, for example that of `buildOrders`.

**Comment by bh2smith** [comment]
If only there was some way of statically analyzing this...

**Comment by bh2smith** [comment]
I googled "enforce JSDoc" and found a few options:

- `eslint-plugin-jsdoc - npm`
- `valid-jsdoc - Rules - ESLint - Pluggable JavaScript linter`
- `require-jsdoc - Rules - ESLint - Pluggable JavaScript linter`
