### ISSUE TITLE
Documentation: 

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#114]
- [ ]  introduction: what is the concept, why do we use the gnosis Safe
- [x]  better documentation of the complete-liquidity-provision script

**Comment by bh2smith** [comment]
If this is half done, is there a branch or a PR that is related to this issue?

**Comment by bh2smith** [comment]
If I understand correctly, the first point here is contained in the tutorial PR: https://github.com/gnosis/dex-docs/pull/15

If this is the case, I think we should close this once it is merged.
