### ISSUE TITLE
[Easy] Inconsistent file name conventions

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#122]
In the scripts directory alone we are using all of `snake_case`, `camelCase` and `kebab-case`. According to this JS style guide it appears that snake_case or kebab-case are the standard. 

I would propose sticking with one or the other, but not both. 

Note that kebab case is used for github repo names and node package naming so maybe we should stick with snake case for filenames to avoid conflict. 

Suggestions?

**Comment by josojo** [comment]
Yeah, let's go with snake_case
