### ISSUE TITLE
Thoughts on verification script for bracket strategy

### ISSUE THREAD

**Issue by cag** [gnosis/dex-liquidity-provision#142]
https://github.com/gnosis/dex-liquidity-provision/blob/deae90ca01af267074fe11efefa81032df3a33c7/scripts/utils/verify_scripts.js#L39

I think this is handled by the next call to `.setProvider`, as Truffle's contract abstraction would automatically try to get the network ID from the provider. I don't remember ever having to set the network ID in my own scripts anyway. Maybe I'm wrong.

https://github.com/gnosis/dex-liquidity-provision/blob/deae90ca01af267074fe11efefa81032df3a33c7/scripts/utils/verify_scripts.js#L62

`artifacts` is ignored in this call.

https://github.com/gnosis/dex-liquidity-provision/blob/deae90ca01af267074fe11efefa81032df3a33c7/scripts/utils/verify_scripts.js#L95

Could simply check:

```js
ownedOrders[0].priceNumerator.mul(ownedOrders[1].priceNumerator).gt(
  ownedOrders[0].priceDenominator.mul(ownedOrders[1].priceDenominator)
)
```

Though the intent would be a bit less clear with a rewrite like that.

Also, should this be `gte` instead of `gt`?

Also. this assumes

```js
ownedOrders[0].buyToken === ownedOrders[1].sellToken &&
    ownedOrders[0].sellToken === ownedOrders[1].buyToken
```

right? Should that also be verified?

---

There are a few additional verification steps that can be done for the bracket traders:

* Runtime bytecode for the proxies can be checked to match an expected proxy's bytecode via `web3.eth.getCode`.
* Could use `getModules` to check for an empty array (https://github.com/gnosis/safe-contracts/blob/0d30c3c748eb085300b6d15d272f6932d376b8a3/contracts/base/ModuleManager.sol#L109)
* Could use `web3.eth.getStorageAt` to check the fallbackHandler and make sure it is the default handler (https://github.com/gnosis/safe-contracts/blob/0d30c3c748eb085300b6d15d272f6932d376b8a3/contracts/base/FallbackManager.sol#L10 and https://github.com/gnosis/safe-contracts/blob/0d30c3c748eb085300b6d15d272f6932d376b8a3/.openzeppelin/mainnet.json#L200)

**Comment by fedgiac** [comment]
Great suggestion, thanks a lot for the help.
Here is a list to track our progress in working with each issue:
- [ ] `.setNetwork` not needed
- [ ] `artifacts` not needed
- [ ] simpler check for bracket profitability
- [ ] `.gte` instead of `.gt`
- [ ] verify buy token and sell token ids in orders
- [ ] check proxy contract bytecodes
- [ ] check that there are no modules
- [ ] check that fallback handler is unchanged

**Comment by fedgiac** [comment]
All comments have been implemented, thanks!

**Comment by bh2smith** [comment]
Closing this as it appears to have been taken care of
