### ISSUE TITLE
different proposer accounts

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#158]
Introduce customized proposer accounts. In this way there would be less risk of our users shooting themselves in the foot.

---
not sure whether it is worth the effort. Investigate effort

**Comment by fedgiac** [comment]
As discussed [here](https://github.com/gnosis/dex-liquidity-provision/pull/157#issuecomment-618969108), this kind of counts as cleanup.

**Comment by josojo** [comment]
I think it is very important that we focus on this task, it even should be part of the tutorial. It's really not good if anyone can propose any transaction to your gnosis-safe and you see them in the interface.
