### ISSUE TITLE
Revise caluclation of the withdrawal amount

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#159]
With the current withdrawal logic, users might only be able to withdraw less than the amount in the pending withdrawal request, and thus the multisend withdraw+transferFundsToMaster would fail.

We should try to use web3.getStorageAt and manually compute the storage position of balanceState[braketAddress] to calculate the right amount.

**Comment by fedgiac** [comment]
`--requestWithdraw` should request maxUint256 unless executed with withdrawal file.
`--withdraw` should not care about the amount.
`--transferFundsToMaster` should handle two cases: `--withdraw` should fetch withdrawable amount from the exchange, and by itself it should keep following the current logic.
