### ISSUE TITLE
Make complete liquidity provision compatible with hardcoded addresses

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#191]
It's natural to hardcode addresses in the complete liquidity provision scripts, but it creates extra risks that were not considered when creating the script. Some ideas:
- add `--brackets` to the command-line arguments, which makes the script skip deployment
- add extra checks, ideally only when `--brackets` is given

**Comment by fleupold** [comment]
I was going to look into this task but have a question:

It seems like we already have a `bracket_orders.js` script that allows to pass existing `--bracket` via the command line.

Isn't this sufficient? Do we also want to have this functionality for `buildTransferApproveDepositFromOrders`? 

Or is this script no longer used and we want to change `complete_liquidity_provision.js` to skip the first step when provided with existing brackets?

**Comment by josojo** [comment]
Yes, you are right Felix, one could always run 
```
placeOrders
--> create a custom made deposit file
buildTransferApproveDepositFromOrders
```
once the brackets are available, instead of the 'complete_liquidity_provision' with the brackets. But in practice, one avoids these 3 time-consuming steps, if one could do it with one step, just to save some time. Its really just a convenience feature, which would have prevented the error from last thursday

**Comment by fleupold** [comment]
So is there a value in having the `bracket_orders.js` and `transfer_approce_deposit.js` scripts by themselves or can they be removed?

Also, how does one create the deposit file you are referring to?

In case we want to use the complete script for this, I assume this tasks captures adding another optional `--bracket` command line option to the complete script and skip fleet deployment if it is specified.
The task description mentions to do some "checks" in that case. Are these the priceCheck and boundCheck that are currently performed in `bracket_orders` script?

**Comment by fedgiac** [comment]
> So is there a value in having the bracket_orders.js and transfer_approce_deposit.js scripts by themselves or can they be removed?

Currently there is none, it has been a long time since they have been used. In the future they could have their own purpose however: at the moment `complete_liquidity_provision.js` is intended to be used for the first deployment of the safes, so `bracket_orders.js` and `transfer_approve_deposit.js` could be used afterwards. `transfer_approve_deposit.js` could also be extended to have a more fine-grained control on how deposits work, for example setting an unlimited allowance, depositing to the brackets but not to the exchange, and so on.

> Also, how does one create the deposit file you are referring to?

A file `automaticallyGeneratedDeposits.json` is automatically created in the root directory when running `complete_liquidity_provision.js`. It contains information about what has been deposited to the exchange in that run and is compatible with both `transfer_approve_deposit.js` and `withdraw.js`.

> The task description mentions to do some "checks" in that case. Are these the priceCheck and boundCheck that are currently performed in bracket_orders script?

No, they are different. A minimum requirement is to check whether the brackets already have orders, which is not done and is not supposed to be done for `bracket_orders.js`.

**Comment by bh2smith** [comment]
> Are these the priceCheck and boundCheck that are currently performed in bracket_orders script?

Yes, both `priceCheck` and `boundCheck` are performed in `bracket_orders.js`

https://github.com/gnosis/dex-liquidity-provision/blob/0848c7197d02b1c8b5e0c900a05153a8c64b7c1d/scripts/bracket_orders.js#L63-L64

I would like to mention that I am actually quite disappointed to see that some of these standalone scripts which were written with the intention that they could be used as components in complete liquidity provision have been abandoned. 

Also, I think they do serve a purpose for responsible future maintenance of bracket strategies (i.e. topping up balances, order cancellation, deletion, placing new orders). I assume that up until now these brackets have not been "cleaned up" in an EVM garbage collection kind of way. For example, my guess is that old brackets deployed would have their funds withdrawn and orders left open.

**Comment by fedgiac** [comment]
I'd like to point out that many checks are already implemented in some form in `scripts/utils/verify_scripts.js`, so it'd be a good idea to have check functions shared among different scripts.
