### ISSUE TITLE
Ignore dust withdrawals

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#192]
We could ignore small amounts when withdrawing funds, since some withdrawals would cost more in gas than the withdrawn amount is worth in terms of value.
This would require however a good definition of "value":
- maintain a list of known tokens and min prices (e.g. DAI will never be worth more than 100$, hence  I can ignore 0.0001DAI (<= 1 cent)).
- fetch token price from somewhere
I'm not sure I like any of the two proposals, but maybe you have some better ideas.

**Comment by josojo** [comment]
I like 
- fetch token price from dex.ag

Even when the price is incorrect, the damage done should be quite low. One could still withdraw them later in another transaction.
