### ISSUE TITLE
Verification scripts for signer

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#193]
A signer must currently trust the executor of the script and sign almost blindly. A verification script could repeat the steps executed by the deployment script and confirm that the (Safe) hash of the transaction is correct.

**Comment by fleupold** [comment]
It seems relatively straightforward to introduce a dry-run parameter and print the transaction hash instead of sending it inside signAndSend.

I will also add an optional nonce argument so that the same nonce as in the original tx can be used.

It's a little bit trickier for deploying the actual fleet of safes. There we rely on event emission to get the contract addresses. In order to dry-run this it would be beneficial to also return them from that function so that we could `.call` it without actually executing it.

Can we easily change the `FleetFactory.sol` code or would this have consequences on the previously created contracts?

Alternatively we could also require to pass in hardcoded brackets (which will eventually skip this step), but it would be nice if the two wouldn't have to be tightly coupled.

@fedgiac @josojo what do you guys think?

**Comment by fedgiac** [comment]
I'm not sure we can easily merge the dry run and the script for the verifier.

I see two implicit assumptions in this approach:
1. the verifier script is run before the script actually deploying the bracket (otherwise `.call` would return new addresses)
2. no other brackets have been created _by the FleetFactory contract_ between when the verifier script runs and the deployer script runs (otherwise the two hashes wouldn't match)

Point 2. is because (to my current understanding) an address is computed deterministically from the address of the creator (in our case `FleetFactory`) and the nonce counting the number of transactions sent from this address.

I think 2 is particulary worrisome as soon as we are not the only ones using the scripts anymore.
Having the nonce as an extra parameter helps, but I'm not sure how the nonce of a contract is exactly computed and if and how a user could retrieve it from some nice interface like Etherscan. Also, it's yet another command-line option to understand.

So I still think the verifier script should read from the event. In this case you can filter based on the fleet owner, and the assumptions become:
1. the verifier script is run _after_ the script actually deploying the bracket
2. no other brackets have been created _with the same owner by the FleetFactory contract_  between when the deployer script runs and the verifier script runs

The second set of assumptions is not exempt from issue: anyone could create in between the deployer and verifier transactions a new fleet with the same owner, thus making the hash check fail. This is still annoying but assumes an active adversary.

In general, it's definitely feasible to change the logic of `FleetFactory.sol`, very little depends on it.

If possible, I'd try to avoid yet another mandatory command-line option taking the newly deployed fleet, since executing the full liquidity command already spans some lines in the terminal. Optional arguments are always welcome on the other hand.

**Comment by fleupold** [comment]
> So I still think the verifier script should read from the event. 

Can you elaborate what this means? Which event are we talking about?

**Comment by fedgiac** [comment]
With this I mean the approach relying on the event emission you mention, so basically have the deployer deploy the new safes and then the verifier read the last event `FleetDeployed` fired by `FleetFactory` filtered by `owner == masterSafe`.

**Comment by fleupold** [comment]
I see and I also understand now why this would imply your 2nd assumption (which I don't think is necessary). I was envisioning that for the real verification script would take `--brackets` as input and thus skip the deployment phase altogether (related to #191).

I understand your concern about too many command-line arguments. Both, the nonce, dry-run and bracket argument would be overall optional but necessary if you want to do a proper verification.

The original script could also print out the command to verify the tx hash in the end and this could then be shared via slack or the like to make it easy to validate.

**Comment by fedgiac** [comment]
Yep, if you use `--brackets` then assumption 2 is not necessary anymore.

The idea of having a copypastable command from the deployer as you say is maybe the best option. My only concern is that as we get used to the process we'd start to skip the step where the verifier actually checks that the command-line options are right and simply blindly run the verification script. As it works right now, Alex and I independently produce the command to be run, we compare the two, and if they match we run it. It would be cool if I could take the command I already built instead of relying on a new one, where there could have been independent copy-paste issues.

**Comment by fleupold** [comment]
In this case we could just print the —bracket —nonce and —dry-run arguments to be shared via slack.

**Comment by fleupold** [comment]
Ok, so this tasks seems blocked on https://github.com/gnosis/dex-liquidity-provision/issues/191 as this task will add the --bracket argument. Then we can add a --dry-run --nonce argument and used in combination that will print out the tx hash.
