### ISSUE TITLE
Replace stableToken with relativeToken

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#231]
The term "stable token" can be misleading as it's not necessary for the stable token to be "stable" in any sense. The only difference between target token and stable token is that the price is always written in terms of amount of stable tokens against one target token. As proposed by Ben, we could use "relative token" instead.

**Comment by josojo** [comment]
I would vote for baseToken and quoteToken, as this is commonly used in finance:
https://www.investopedia.com/terms/b/basecurrency.asp

**Comment by bh2smith** [comment]
Which one? base or quote? I'm going to go with base.

**Comment by josojo** [comment]
With my logic, targetToken would become the baseToken and stableToken the quoteToken, right? Since the price is currently given as: [ targetToken ] / [ stableToken ].

**Comment by bh2smith** [comment]
If I were to change both, then I imagine the opposite:

`targetToken` is the volatile one and subject to being "quoted" while `stableToken` is the `baseToken`.

**Comment by bh2smith** [comment]
However, according to others that I have spoken with in my example above EUR is the "base token" and CAD is the "quote token", so I suppose your suggestion @josojo is correct.

**Comment by bh2smith** [comment]
I find it very strange that ETH is going to become the base token and DAI will become the quote token.

**Comment by bh2smith** [comment]
I think this particular line in the code base is a reasonable argument/proof for converting `target` to `quote` and `stable` to `base`:

https://github.com/gnosis/dex-liquidity-provision/blob/4d10b440593cb56858b1b9d22243f700a0dd8d5f/scripts/utils/price_utils.js#L20

Since it will become:

```
all prices are of the form: 1 quote token = "price" base tokens
```

for example,

```
all prices are of the form: 1 ETH = "price of ETH" DAI
```

**Comment by bh2smith** [comment]
Here are some other comments in the code that would suggest target become quote and stable become base:

https://github.com/gnosis/dex-liquidity-provision/blob/37cf28e6440e7af0245675458f1e661a1ea9f2ad/scripts/utils/trading_strategy_helpers.js#L219-L220

**Comment by fedgiac** [comment]
My understanding from [Wikipedia](https://en.wikipedia.org/wiki/Currency_pair) is that Alex is right and in our code "target"="base" and "stable"="quote". This is also considering your examples, since the price tells you by definition "1 base currency = price quote currency".
Without any context I'd also have expected them to work the other way around however.

**Comment by josojo** [comment]
8500 XBT/USD => 8500 USD = 1 BTC. => 8500 [stableToken] = 1 [targetToken]
110 EUR/JPY => 100JPY = 1 EUR

Hence, xbt and eur should be the base token = target Token.

**Comment by bh2smith** [comment]
> 8500 [stableToken] = 1 [targetToken]

XBT is not the "stable" one here.

**Comment by bh2smith** [comment]
Ya ok. Not sure why I am so confused here.

**Comment by anxolin** [comment]
This is a conversation we periodically have every couple of weeks 😅

I agree with the comment of @josojo above, just I'm confused why we call it base and target.
We usually refer to them as base and quote currencies.

What A/B is the same as A-B, and it’s a market where A is the base, and B is the quote. 
Normally the quote is something the trader is comfortable on seeing price in —> like USD
Is the currency the trader will use in the transaction.

When you say **A-B price is 100**, you mean **A Costs 100 B** , in other words **1 A = 100 B**

Please @Rafanator correct if it's not right

**Comment by Rafanator** [comment]
@anxolin you are 100% correct: 

A is the base currency, B is quote currency (You use B to quote the price of 1(A), hence the name) 

Also, in trading A/B or A-B are fine, traders don't care.
