### ISSUE TITLE
Eliminate "Warning: possible unsupported command line option"

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#247]
For ages, we have been ignoring this gross warning regarding our script arguments. Lets deal with it!

```sh
> Warning: possible unsupported (undocumented in help) command line option: --baseTokenId,--quoteTokenId,--lowestLimit,--highestLimit,--currentPrice,--masterSafe,--depositBaseToken,--depositQuoteToken,--fleetSize,--verify,--nonce,--brackets
```

**Comment by fedgiac** [comment]
I'd also love this, but last time I checked this was not really supported by Truffle.

**Comment by bh2smith** [comment]
I will find a way!

**Comment by fedgiac** [comment]
It doesn't look like Truffle supports silencing this warning, but I see they might be willing to reconsider the current default behavior if we were to contribute: https://github.com/trufflesuite/truffle/issues/2381.

**Comment by bh2smith** [comment]
Nice find @fedgiac! Let’s evaluate if and when we can do this next week!
