### ISSUE TITLE
Improve Tests & Assertions

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#28]
Currently our tests only ensure that the desired batched transactions are successful. However, even these tests are slightly insufficient since we don't even check the buy-sell amount on the batched order placement. Of course it should not be necessary to compare all values of our orders since the Exchange contracts are themselves tested, but we should, at the very least check the the correct number and value for `orderIDs` are recorded.

Furthermore, we should include more assertions in scripts themselves:

1. Transfer-Approve-Deposit
    - Assert that master safe has sufficient balance (ask to override)
    - Assert that each slave is owned by master
    - Assert that tokens are listed on the exchange (not absolutely necessary)

2. Order Placement
    - Assert that tokens are listed on the exchange        
    - Assert that each slave is owned by master

Once these assertions are imposed, our truffle tests should also test failures (i.e. Test that helper scripts fail on above assertions)

**Comment by josojo** [comment]
All these tests have been implemented. The assertion that tokens are listed on the exchange is implemented indirectly, as fetching token info will fail if the tokens are not listed on the exchange.
