### ISSUE TITLE
Rewrite depositList file format

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#30]
Currently the deposit list is not very ergonomic in the sense that assertions regarding slave accounts and token balances need to be fetched from the EVM multiple times over. In many of the specific use cases the token address is repeated several times to indicate that several trader accounts want to deposit the same token. 

Could take the deposit list, gather the distinct set of accounts and tokens so they are only fetched once.

Such an update would also help when making assertions on token information that we only fetch each distinct token from the EVM once.

Loop now looks like for `d in deposit` while it could be more like:

```
for token in deposit tokens:
     // fetch token and make assertion
     for account in accounts depositing token: 
```

An example, file format could look as follows:

```
deposits = [
    "tokenAddress": [
        {
            "user": "0x...1",
            "amount": "10000"
        },
        {
            "user": "0x...2",
            "amount": "10000"
        },
    ],
    "otherTokenAddress": [
        {
            "user": "0x...1",
            "amount": "10000"
        },
        {
            "user": "0x...2",
            "amount": "10000"
        },
    ]
]
```

Although this is kind of a hybrid python dictionary/JS object. Looking for suggestions @josojo and/or @fedgiac.

**Comment by josojo** [comment]
@fedgiac I would be in favor of not changing the depostfile format. How do you feel about it?

**Comment by fedgiac** [comment]
My main issue with the deposit file is that it has to be manually created and manipulated. I think we should create a script to automatically populate the deposit file (as far as I understand the deposits are already handled in the new script that creates the brackets, so the only thing missing is a script to modify the deposit file if we want to add funds to some brackets).

If the scripts are there, then the format of this file doesn't matter: the only advantage of the new format is not querying the blockchain for the same info multiple times, but the amount of queries we make is likely far below any reasonable rate limit of any web3 provider anyway.

**Comment by josojo** [comment]
Yeah, it would be great to have a script that just handles arbitrary deposits to a list of bracket-traders.

The script could work like that:
inputs --current price , --list of existing bracket-traders, --investement for brackets

logic:
check all the bracket-traders and their orders prices,
split the deposit for all brackets-traders which would sell the tokens above current price.

**Comment by bh2smith** [comment]
We can also avoid redundant queries by simply accumulating and fetching the set of tokens just before entering the deposit loop.

**Comment by fedgiac** [comment]
The motivation for this issue is moot since #71, for this reason we decided to keep the format of `depositList` basically unchanged.
