### ISSUE TITLE
[CI] EndtoEnd Testing our Scripts (Rinkeby)

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#314]
We have encountered many sloppy refactoring recently in which files were renamed or functions moved that we not caught by CI. Not only this, but we are still using unsafe JS. I think it is time to switch to TS here considering that the scripts here are responsible for some potentially serious transactions.

Another good example of this is in `airdrop.js` where we have a few optional parameters https://github.com/gnosis/dex-liquidity-provision/pull/309#discussion_r44088586 this would come in handy.

For example.

- [ ] Test synthetix bot (bash place orders, run bot see that it places an order.... requires price estimator to reflect order placed).

**Comment by fedgiac** [comment]
I consider "better CI" and "move to TS" two different, independent issues.
Our problem with CI is that the scripts themselves are not tested, only the functions we use. as a consequence to that, when we change function names, parameters, or file paths, the scripts silently break. I see two solutions:
1. we find out some tool that automatically checks all imports in a JS file.
2. we create proper testing infrastructure for the scripts.

I personally prefer 2, but it has been deemed a low priority so far. In any case, I'll ignore this issue and focus on creating the infrastructure needed to migrate to TS next.

**Comment by bh2smith** [comment]
We have already agreed that we cannot test the scripts and found a reasonable work around. By migrating to TS we would now have code that is compiled to JS and thus our CI would fail if the we have broken imports.

**Comment by fedgiac** [comment]
Did we agree that we can't test the script?
I liked the idea of making all our scripts look like:
```
const functionality = require('./wrapper/functionality.js')(web3, artifacts)
const { signAndSend } = require("./utils/gnosis_safe_server_interactions")(web3, artifacts)
const { promptUser } = require("./utils/user_interface_helpers")

module.exports = async (callback) => {
  try {
    await functionality(signAndSend, promptUser)
    callback()
  } catch (error) {
    console.error(error)
    callback(error)
  }
}
```

And then we run tests for 
```    await functionality(execTransaction, mockPrompt)```

So you say that Typescript automatically checks imports? That's great, I don't know why this isn't already done for JS!
If you don't mind I'd keep the other issue open and write technical details on the migration there. I like that I can edit the first message so that it's kept up to date with the current state of the migration. I could rename it to "Technical details on TS migration" if you wish.
