### ISSUE TITLE
TransferApproveDeposit - Partially Executed

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#348]
This transaction has filed to complete: Successfully only sending funds into the bracket and possibly also approving the exchange for the deposit amount.

https://etherscan.io/tx/0xa538f4a0afa57118c14100ac538b0dbb2c094efddb4393aa48ea3e9cb637aa6b/advanced#internal

It seems the transaction ran out of gas at this point and now the funds are in the bracket.

**Comment by fedgiac** [comment]
Same issue described in #350.
