### ISSUE TITLE
Replace parallized promises with batched promises

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#400]
Every time the internet connection is bad or infra has a bad day, people are complaining about rpc call failures.

We should batch our RPC calls instead of parallelizing them. This [Smartcontract](https://github.com/makerdao/multicall/blob/master/src/Multicall.sol) could make it easy. It seems to be an industry standard for frontend. Uniswap and maker are using it.

**Comment by fedgiac** [comment]
Implementing [web3 batch requests](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#batchrequest) did not help with this issue. See PR #435.
