### ISSUE TITLE
Make request_withdraws cheaper

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#417]
Currently, during request_withdrawals, we are requesting withdrawals for all tokens on all brackets with unlimited numbers. This is good, as it stops all trading activity and ensure that everything can be withdrawn in the next step. 

Though it might be a little bit over the edge, as many brackets ( e.g. the ones with limitprice> 10% from the current price) won't trade with a very high likelihood. I think we don't have to request on these bracket with both tokens, if the bracket only holds one token

**Comment by bh2smith** [comment]
This seems like we could changing this segment in the request:

https://github.com/gnosis/dex-liquidity-provision/blob/15b4d843ed6060aea92659e9d42ea12b8e8b6fc0/scripts/wrapper/withdraw.js#L100-L102

and simply using what we use in the claim. My only concern here, is not requesting the max amount of everything and finding that the balances have changed during the next batch... then the claim would no longer fetch everything.

**Comment by fedgiac** [comment]
FIxed in #464.
