### ISSUE TITLE
Write Safe Artefacts with deployed addresses on Migration

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-liquidity-provision#517]
Our Safe Contracts are currently not written to the artefacts folder with their originally deployed addresses. On migration, we instead add the addresses manually to `networks.json` and inject them into the freshly compiled artefacts.

This is dangerous as we would not notice address changes, e.g. when the Safe upgrades.

@rmeissner does the Safe expose a method to get the currently deployed artefact from within it's own package that we could use in our JS rather than `const GnosisSafe = artifacts.require("GnosisSafe")`? I believe the reason we use the artefact from our local build folder is so that we can access the ganache deployment during tests.

For GP we "copy" the artefact whenever we do a migration cf.

https://github.com/gnosis/dex-liquidity-provision/blob/5504808e71ba9b3f3950cac806b2b8bb46f2db7f/migrations/2_dev_dependencies.js#L8-L18

However, this would also not detect upgrades to the underlying contract unless we re-migrate.

**Comment by rmeissner** [comment]
you mean something like https://github.com/gnosis/safe-modules/blob/master/allowances/test/allowanceSingle.js#L5 ?

**Comment by fleupold** [comment]
Yes, I think the issue we had with this approach is that we still need to deploy the dependency e.g. when running everything locally on ganache. In this case e.g. our scripts would have to check whether to use the local artefact or the artefact from the npm package.
