### ISSUE TITLE
Inconsistent input/output relationship in fetchTokenInfo*

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#98]
The functions `fetchTokenInfo*` take an array and return a dictionary. This should probably be changed to avoid confusion.

**Comment by bh2smith** [comment]
I don't believe this is confusing at all.

observe that the following function takes an array and returns a number:

```py
def max_element(arr: List[int]) -> int:
    return max(arr)
```

**Comment by bh2smith** [comment]
Are we planning to do this @fedgiac ?

**Comment by fedgiac** [comment]
Overall these functions work well enough, so I'd leave them as they are for the time being.
